save: false

allowBuilds:
  '@parcel/watcher': true
  'core-js': true
  'esbuild': true
  'hugo-bin': true

minimumReleaseAgeExclude:
  - '@types/three'
  - 'esbuild-plugin-glsl'
  - 'eslint-config-aether'
  - 'spatial-controls'
  - 'three'
