import {
	AddBlendFunction,
	AlphaBlendFunction,
	AverageBlendFunction,
	ColorBlendFunction,
	ColorBurnBlendFunction,
	ColorDodgeBlendFunction,
	DarkenBlendFunction,
	DifferenceBlendFunction,
	DivideBlendFunction,
	DstBlendFunction,
	ExclusionBlendFunction,
	HardLightBlendFunction,
	HardMixBlendFunction,
	HueBlendFunction,
	InvertBlendFunction,
	InvertRGBBlendFunction,
	LightenBlendFunction,
	LinearBurnBlendFunction,
	LinearDodgeBlendFunction,
	LinearLightBlendFunction,
	LuminosityBlendFunction,
	MixBlendFunction,
	MultiplyBlendFunction,
	NegationBlendFunction,
	OverlayBlendFunction,
	PinLightBlendFunction,
	ReflectBlendFunction,
	SaturationBlendFunction,
	SrcBlendFunction,
	ScreenBlendFunction,
	SoftLightBlendFunction,
	SubtractBlendFunction,
	VividLightBlendFunction
} from "postprocessing";

const blendFunctionArray = [
	new AddBlendFunction(),
	new AlphaBlendFunction(),
	new AverageBlendFunction(),
	new ColorBlendFunction(),
	new ColorBurnBlendFunction(),
	new ColorDodgeBlendFunction(),
	new DarkenBlendFunction(),
	new DifferenceBlendFunction(),
	new DivideBlendFunction(),
	new DstBlendFunction(),
	new ExclusionBlendFunction(),
	new HardLightBlendFunction(),
	new HardMixBlendFunction(),
	new HueBlendFunction(),
	new InvertBlendFunction(),
	new InvertRGBBlendFunction(),
	new LightenBlendFunction(),
	new LinearBurnBlendFunction(),
	new LinearDodgeBlendFunction(),
	new LinearLightBlendFunction(),
	new LuminosityBlendFunction(),
	new MixBlendFunction(),
	new MultiplyBlendFunction(),
	new NegationBlendFunction(),
	new OverlayBlendFunction(),
	new PinLightBlendFunction(),
	new ReflectBlendFunction(),
	new SaturationBlendFunction(),
	new SrcBlendFunction(),
	new ScreenBlendFunction(),
	new SoftLightBlendFunction(),
	new SubtractBlendFunction(),
	new VividLightBlendFunction()
];

export const blendFunctions = Object.fromEntries(
	blendFunctionArray.map(x => [x.name, x])
);
