name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: true
      - name: Build and test
        run: pnpm -r test
      - name: Publish
        uses: JS-DevTools/npm-publish@v4
        with:
          provenance: true
          ignore-scripts: true
      - name: Deploy pages
        run: |
          pnpm run -r deploy
          pnpm run gzip
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean-exclude: |
            public
